name: 抖音火山

on:
    workflow_dispatch:
    schedule:
        - cron: "*/5 * * * *"
    watch:
        types: [started]

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行【抖音火山】"
              run: |
                  node huoshan.js
              env:
                    playurl: ${{ secrets.playurl }}
                    playheader: ${{ secrets.playheader }}
                    playbody: ${{ secrets.playbody }}
                    hsurl : ${{ secrets.hsurl }}
                    hsheader: ${{ secrets.hsheader }}
                    hsbody : ${{ secrets.hsbody}}


                    PUSH_KEY: ${{ secrets.PUSH_KEY }}
                    BARK_PUSH: ${{ secrets.BARK_PUSH }}
                    TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
                    TG_USER_ID: ${{ secrets.TG_USER_ID }}
                    BARK_SOUND: ${{ secrets.BARK_SOUND }}
                    DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
                    DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
                    IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
