# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 读阅QQ

on:
    # push:
    #     branches:
    #         - main
    schedule:
        - cron: "*/30 0-12 * * *"
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: npm install
              run: |
                  npm install
            - name: "运行 【阅读QQ】"
              run: |
                  node Task/QQread.js
        env:
             QQ_QQreadURL: ${{ secrets. QQ_QQreadURL }}
             SCKEY: ${{ secrets.SCKEY }}
             BARK_PUSH: ${{ secrets.BARK_PUSH }}
             PUSH_KEY: ${{ secrets.PUSH_KEY }}
             TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
             TG_USER_ID: ${{ secrets.TG_USER_ID }}

