 name: 走路赚

 on:
   workflow_dispatch:
   schedule:
     - cron: '*/5 * * * *'
   watch:
     types: started
   repository_dispatch:
     types: _

 jobs:
   build:
     runs-on: ubuntu-latest
     if: github.event.repository.owner.id == github.event.sender.id
     env:
          XIAOMUYUHEADER: ${{ secrets. XIAOMUYUHEADER }}
          IBOXPAYBODY: ${{ secrets. IBOXPAYBODY }}
          TURNTABLRURL: ${{ secrets. TURNTABLRURL }}
          TURNTABLRHEADER: ${{ secrets. TURNTABLRHEADER }}
          DOUBLEHEADER: ${{ secrets. DOUBLEHEADER }}
          CARDBODY: ${{ secrets. CARDBODY }}
          MEMBERBODY: ${{ secrets. MEMBERBODY }}
          DRINKBODY: ${{ secrets. DRINKBODY }}
     steps:
       - name: Checkout
         run: |
           git clone https://github.com/DD-D1/Script.git ~/Script
       - name: Use Node.js 12.x
         uses: actions/setup-node@v1
         with:
           node-version: 12.x
       - name: npm install
         if: env.XIAOMUYUHEADER
         run: |
           cd ~/Script
           npm install
       - name: '运行 【走路赚】'
         if: env.XIAOMUYUHEADER
         run: |
           cd ~/Script
           node zoulusign.js
         env:
           TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
           TG_USER_ID: ${{ secrets.TG_USER_ID }}
